# Generated by Django 5.0.8 on 2026-06-26 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField()),
                ('overview', models.TextField()),
                ('why_choose', models.TextField(blank=True)),
                ('who_should_apply', models.TextField(blank=True)),
                ('key_highlights', models.TextField(blank=True)),
                ('documents_required', models.TextField(blank=True)),
                ('process_steps', models.TextField(blank=True)),
                ('timeline', models.TextField(blank=True)),
                ('pricing_note', models.TextField(blank=True)),
                ('faq', models.TextField(blank=True)),
                ('starting_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_timeline', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('business_type', models.CharField(blank=True, max_length=120)),
                ('customer_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('DOCS_PENDING', 'Documents Pending'), ('UNDER_REVIEW', 'Under Review'), ('SUBMITTED', 'Submitted'), ('QUERY_RAISED', 'Query Raised'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=30)),
                ('payment_status', models.CharField(choices=[('NOT_PAID', 'Not Paid'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='NOT_PAID', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customer_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_requests', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requirements_app.service')),
            ],
            options={
                'verbose_name': 'Customer Request',
                'verbose_name_plural': 'Customer Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='request_documents/')),
                ('verified', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='requirements_app.customerrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Document',
                'verbose_name_plural': 'Request Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requirements_app.servicecategory'),
        ),
    ]
