trigger:
 branches:
  include:
  - main
  - feature

pr:
  branches:
    include:
      - main

pool:
  name: linux-build-pool

stages:
  stage: Build
  jobs:
  - steps:
      script: "build Appication"
  stage: test
  dependsOn: Build
  succeeded: true


